### ISSUE TITLE
I8K causes lag when getting status of fan speed 

### ISSUE THREAD

**Issue by Paxy** [groeck/i8k#2]
This bug is reported on many support pages, like https://bugs.launchpad.net/i8kutils/+bug/1405003.

On Dell Inspiron N7110, Ubuntu 14 while controlling fan via i8kmon service system freezes for about second, fan changes speed, and system resume its works. 
This bug can be reproduced with simple:
                          cat /proc/i8k
which shows     1.0 A06 GK4PSQ1 59 -22 1 -22 3134 -1 -22 

This Bug is isolated to I8K driver, as if it is removed from system, lag do not occur.

I8Kutils added module for function execution time assessment:
root@paxy-ubuntu:/usr/src/i8kutils# ./probe_i8k_calls_time 
functions time
i8k_get_bios_version() = 0.507588
i8k_get_machine_id() = 0.000002
i8k_get_cpu_temp() = 0.002212
i8k_get_fan_status() = 0.000184
i8k_get_fan_status() = 0.002165
i8k_get_fan_speed() = 0.000179
i8k_get_fan_speed() = 0.502124
i8k_get_power_status() = 0.000303
i8k_get_fn_status() = 0.000213
i8k_set_fan() = 0.000211
i8k_set_fan() = 0.000204
i8k_set_fan() = 0.000215
i8k_set_fan() = 0.504249
i8k_set_fan() = 0.504910
i8k_set_fan() = 0.504816

This is latest, from this trunk, i8k drivers, and i8kutils version 1.42.

**Comment by groeck** [comment]
On 10/09/2015 01:13 AM, Paxy wrote:
> This bug is reported on many support pages, like https://bugs.launchpad.net/i8kutils/+bug/1405003.
>
> On Dell Inspiron N7110, Ubuntu 14 while controlling fan via i8kmon service system freezes for about second, fan changes speed, and system resume its works.
> This bug can be reproduced with simple:
> cat /proc/i8k
> which shows 1.0 A06 GK4PSQ1 59 -22 1 -22 3134 -1 -22
>
> This Bug is isolated to I8K driver, as if it is removed from system, lag do not occur.
>
> I8Kutils added module for function execution time assessment:
> root@paxy-ubuntu:/usr/src/i8kutils# ./probe_i8k_calls_time
> functions time
> i8k_get_bios_version() = 0.507588
> i8k_get_machine_id() = 0.000002
> i8k_get_cpu_temp() = 0.002212
> i8k_get_fan_status() = 0.000184
> i8k_get_fan_status() = 0.002165
> i8k_get_fan_speed() = 0.000179
> i8k_get_fan_speed() = 0.502124
> i8k_get_power_status() = 0.000303
> i8k_get_fn_status() = 0.000213
> i8k_set_fan() = 0.000211
> i8k_set_fan() = 0.000204
> i8k_set_fan() = 0.000215
> i8k_set_fan() = 0.504249
> i8k_set_fan() = 0.504910
> i8k_set_fan() = 0.504816
>
> This is latest, from this trunk, i8k drivers, and i8kutils version 1.42.
>

Well known problem, seen on some Dell systems. Some of mine are affected as well.
The problem is with Dell's SMM code. The system feeezes whenever the fan speed
is read (the 0.5 seconds times above). Only solution known to me is to not use
the i8k driver.

Guenter

**Comment by dabreese00** [comment]
In case someone else has this problem in the future and comes across this bug report, it seems i8k is renamed to dell_smm_hwmon in newer kernels, so you may need to blacklist "dell_smm_hwmon" instead of "i8k".
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=a5afba16c641dc1dda837cfc32dea1e37666d31a

**Comment by lumiera** [comment]
Is there any way to fix this freeze other than unloading/blacklisting dell-smm-hwmon?

**Comment by groeck** [comment]
No.
